options:
  askImageFilename: false
  spellcheck: true
  lineNumbers: true
  imagePath: _posts/Oracle-RAC-12cR2安装手册-4-数据库软件的安装
  imagePrefix: database-software-installation-
editor:
  inputStyle: contenteditable
  spellcheck: true
  lineNumbers: true
