options:
  askImageFilename: false
  spellcheck: true
  lineNumbers: true
  imagePath: _posts/Oracle-RAC-12cR2安装手册-5-数据库实例的创建
  imagePrefix: database-instance-creation-
editor:
  inputStyle: contenteditable
  spellcheck: true
  lineNumbers: true
