nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: https://www.going-link.com

projects_url: https://www.going-link.com

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/JayceLau
        twitter: https://twitter.com/JayceLau
    show_all_posts: false
    post_count: 10
    highlight: rainbow

# RSS
rss: 

# Plugins
plugins:
    disqus_shortname: JR4ever 
# Disqus Comments Shortname
    google_analytics: UA-100497343-1 
# enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
